drop table if exists member CASCADE;
drop table if exists businessTimes CASCADE;
drop table if exists holidays CASCADE;

create table member
(   name varchar(255),
    owner varchar(255),
    description varchar(255),
    level bigint generated by default as identity,
    address varchar(255),
    phone varchar(255),
    primary key (level)
);

create table businessTimes
(   name varchar(255),
    day varchar(10),
    open varchar(10),
    close varchar(10)
);

create table holidays
(   level bigint,
    holiday date
);
